# Generated by Django 4.0.2 on 2022-02-24 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='n1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pan', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='n2',
            fields=[
                ('n1_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='siva.n1')),
                ('age', models.IntegerField()),
                ('adhar', models.IntegerField()),
            ],
            bases=('siva.n1',),
        ),
        migrations.CreateModel(
            name='n3',
            fields=[
                ('n2_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='siva.n2')),
                ('salary', models.IntegerField()),
            ],
            bases=('siva.n2',),
        ),
    ]
