# Generated by Django 4.0.2 on 2022-02-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='real',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('pancard', models.IntegerField()),
                ('village', models.CharField(max_length=50)),
                ('adhar', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='somu',
        ),
    ]
