# Generated by Django 4.0.2 on 2022-02-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanth', '0002_real_delete_somu'),
    ]

    operations = [
        migrations.CreateModel(
            name='rb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('pancard', models.IntegerField()),
                ('passport', models.IntegerField()),
                ('local', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
